ignore-build-dependencies = true
ignore-dev-dependencies = true
no-clearly-defined = true

accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSL-1.0",
    "ISC",
    "CDDL-1.0",
    "MPL-2.0",
    "NCSA",
    "Unicode-3.0",
    "WTFPL",
    "Zlib",
]
