[package]
name = "interactive-shell"
description = "Shell"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.79"
log = "0.4.20"
rustyline = "13.0.0"
shell = { path = "../shell" }
