[package]
name = "interactive-shell"
version = "0.1.0"
edition = "2021"
description = "Shell"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
rustyline = "12.0.0"
shell = { path = "../shell" }