[package]
name = "interactive-shell"
description = "Shell"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.79"
log = "0.4.20"
rustyline = { version = "13.0.0", features = ["derive"] }
parser = { path = "../parser" }
shell = { path = "../shell" }
