[package]
name = "brush-interactive-shell"
description = "Shell"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "interactive_shell"
bench = false

[lints]
workspace = true

[dependencies]
anyhow = "1.0.81"
brush-parser = { path = "../parser" }
brush-shell = { path = "../shell" }
log = "0.4.21"
rustyline = { version = "14.0.0", features = ["derive"] }
