mod arithmetic;
mod builtin;
mod builtins;
mod commands;
mod completion;
mod context;
mod env;
mod error;
mod escape;
mod expansion;
mod extendedtests;
mod interp;
mod jobs;
mod namedoptions;
mod openfiles;
mod options;
mod patterns;
mod prompt;
mod regex;
mod shell;
mod users;
mod variables;

pub use completion::Completions;
pub use error::Error;
pub use interp::ExecutionResult;
pub use shell::{CreateOptions, Shell};
