mod arithmetic;
mod builtin;
mod builtins;
mod context;
mod env;
mod error;
mod expansion;
mod extendedtests;
mod interp;
mod jobs;
mod namedoptions;
mod openfiles;
mod options;
mod patterns;
mod prompt;
mod shell;
mod variables;

pub use error::Error;
pub use interp::ExecutionResult;
pub use shell::{CreateOptions, Shell};
