[package]
name = "parser"
description = "Parser"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.75"
log = "0.4.20"
peg = "0.8.2"
utf8-chars = "3.0.1"

[dev-dependencies]
assert_matches = "1.5.0"
