[package]
name = "brush-experimental-builtins"
description = "*EXPERIMENTAL builtins for a POSIX/bash shell (used by brush-shell)"
version = "0.1.0"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
# usage-rs requires rustc 1.91.
rust-version = "1.91"

[lib]
bench = false

[features]
default = ['builtin.save']
'builtin.save' = ["brush-core/serde", "dep:serde_json"]

[lints]
workspace = true

[dependencies]
brush-core = { version = "^0.5.0", path = "../brush-core" }
brush-builtin-usage = { version = "^0.1.0", path = "../brush-builtin-usage" }
brush-builtin-utils = { version = "^0.1.0", path = "../brush-builtin-utils", default-features = false }
usage = { package = "usage-rs", version = "6.11.1" }
serde_json = { version = "1.0.149", optional = true }
