#
# This workflow was based on https://docs.zizmor.sh/integrations/
#

name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

# Only allow one run of the workflow per branch / PR at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: zizmor latest via zizmor-action
    runs-on: ubuntu-latest
    permissions:
      security-events: write # needed for SARIF uploads
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Reporting pass: uploads SARIF to code scanning, giving us stateful
      # analysis and incremental triage in the Security tab. Does not fail
      # with non-zero result but reports them.
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
